
--- Main theme config
---@class PosterpoleConfig
---@field transparent? boolean
---@field dim_inactive? boolean
---@field brightness? integer
---@field selected_tab_highlight? boolean
---@field fg_saturation? integer
---@field bg_saturation? integer
---@field adaptive_brightness? AdaptiveConfig
---@field colors? PaletteColors
---@field lualine? LualineConfig
---@field custom_groups? CustomGroupsConfig
---
--- Lualine config
---@class LualineConfig
---@field transparent? boolean
---
--- Custom Highlight Groups
---@class CustomGroupsConfig
---@field posterpole table<string, HighlightObject>
---
---@class HighlightObject
---@field fg? Color
---@field bg? Color

---Adaptive config
---@class AdaptiveConfig
---@field enabled boolean
---@field max_brightness? integer
---@field min_brightness? integer
---@field daylight_duration? integer
---@field noon_time? integer

--- Color object
---@class Color
---@field hex? string
---@field cterm? integer

--- GUI colors
---@class Colors
---@field mainGray? Color
---@field mainBlack? Color
---@field mainYellow? Color
---@field mainOrange? Color
---@field mainWhite? Color
---@field mainGreen? Color
---@field mainCyan? Color
---@field mainBlue? Color
---@field mainPurple? Color
---@field mainRed? Color
---@field deepRed? Color
---@field deepGreen? Color
---@field brightGreen? Color
---@field brightGray? Color
---@field bgColor? Color
---@field bgColorNC? Color
---@field bgDarkColor? Color
---@field brightTermBlack? Color
---@field brightTermBlue? Color
---@field brightTermCyan? Color
---@field brightTermGreen? Color
---@field brightTermMagenta? Color
---@field brightTermRed? Color
---@field brightTermWhite? Color
---@field brightTermYellow? Color
